// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using POSCartService.Data;

#nullable disable

namespace POSCartService.Data.Migrations
{
    [DbContext(typeof(PosCartDbContext))]
    [Migration("20260912184333_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("POSCartService.Models.Anulacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AutorizadoPor")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VentaId")
                        .IsUnique();

                    b.ToTable("Anulaciones");
                });

            modelBuilder.Entity("POSCartService.Models.ItemVenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("PesoKg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("ItemsVenta");
                });

            modelBuilder.Entity("POSCartService.Models.Pago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Metodo")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Vuelto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("VentaId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("POSCartService.Models.Turno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AbiertoAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CajeroId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CerradoAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoApertura")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("MontoCierre")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CajeroId");

                    b.HasIndex("SucursalId");

                    b.HasIndex("TenantId");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("POSCartService.Models.Venta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CajeroId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<decimal>("Impuestos")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("TurnoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CajeroId");

                    b.HasIndex("SucursalId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TurnoId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("POSCartService.Models.Anulacion", b =>
                {
                    b.HasOne("POSCartService.Models.Venta", "Venta")
                        .WithOne("Anulacion")
                        .HasForeignKey("POSCartService.Models.Anulacion", "VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("POSCartService.Models.ItemVenta", b =>
                {
                    b.HasOne("POSCartService.Models.Venta", "Venta")
                        .WithMany("Items")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("POSCartService.Models.Pago", b =>
                {
                    b.HasOne("POSCartService.Models.Venta", "Venta")
                        .WithMany("Pagos")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("POSCartService.Models.Venta", b =>
                {
                    b.HasOne("POSCartService.Models.Turno", "Turno")
                        .WithMany("Ventas")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("POSCartService.Models.Turno", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("POSCartService.Models.Venta", b =>
                {
                    b.Navigation("Anulacion");

                    b.Navigation("Items");

                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
