// <auto-generated />
using System;
using AnalyticsNotificationService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnalyticsNotificationService.Data.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20260912181724_InitialAnalyticsSchema")]
    partial class InitialAnalyticsSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnalyticsNotificationService.Models.Alerta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado");

                    b.Property<Guid?>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Umbral")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("umbral");

                    b.Property<decimal>("ValorActual")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("valor_actual");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_alertas_tenant");

                    b.HasIndex("TenantId", "Estado")
                        .HasDatabaseName("idx_alertas_tenant_estado");

                    b.ToTable("alertas");
                });

            modelBuilder.Entity("AnalyticsNotificationService.Models.HistorialEnvio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("destinatario");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_historial_envios_tenant");

                    b.HasIndex("TenantId", "Timestamp")
                        .HasDatabaseName("idx_historial_envios_tenant_timestamp");

                    b.ToTable("historial_envios");
                });

            modelBuilder.Entity("AnalyticsNotificationService.Models.KPIVenta", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_id");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("CantTransacciones")
                        .HasColumnType("integer")
                        .HasColumnName("cant_transacciones");

                    b.Property<decimal>("TicketPromedio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ticket_promedio");

                    b.Property<decimal>("TotalVentas")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_ventas");

                    b.HasKey("TenantId", "SucursalId", "Fecha");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_kpi_ventas_tenant");

                    b.HasIndex("TenantId", "Fecha")
                        .HasDatabaseName("idx_kpi_ventas_tenant_fecha");

                    b.HasIndex("TenantId", "SucursalId")
                        .HasDatabaseName("idx_kpi_ventas_tenant_sucursal");

                    b.ToTable("kpi_ventas");
                });
#pragma warning restore 612, 618
        }
    }
}
