// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaxComplianceService.Data;

#nullable disable

namespace TaxComplianceService.Data.Migrations
{
    [DbContext(typeof(TaxDbContext))]
    [Migration("20260911165140_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaxComplianceService.Models.ConfiguracionFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FolioActual")
                        .HasColumnType("bigint");

                    b.Property<long>("FolioMaximo")
                        .HasColumnType("bigint");

                    b.Property<string>("PaisEntidadFiscal")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<decimal>("PorcentajeImpuesto")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "TipoDocumento");

                    b.ToTable("ConfiguracionesFiscales");
                });

            modelBuilder.Entity("TaxComplianceService.Models.DocumentoTributario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoAutorizacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ConfiguracionFiscalId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContenidoXml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EmitidoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PENDIENTE");

                    b.Property<decimal>("MontoImpuesto")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint");

                    b.Property<int>("Reintentos")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguracionFiscalId");

                    b.HasIndex("TenantId", "Numero")
                        .IsUnique();

                    b.ToTable("DocumentosTributarios");
                });

            modelBuilder.Entity("TaxComplianceService.Models.DocumentoTributario", b =>
                {
                    b.HasOne("TaxComplianceService.Models.ConfiguracionFiscal", "ConfiguracionFiscal")
                        .WithMany("Documentos")
                        .HasForeignKey("ConfiguracionFiscalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfiguracionFiscal");
                });

            modelBuilder.Entity("TaxComplianceService.Models.ConfiguracionFiscal", b =>
                {
                    b.Navigation("Documentos");
                });
#pragma warning restore 612, 618
        }
    }
}
