apiVersion: v1
kind: Service
metadata:
  name: postgres-tenant
spec:
  ports:
  - port: 5432
  selector:
    app: postgres-tenant
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-tenant
  template:
    metadata:
      labels:
        app: postgres-tenant
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "tenant_db"
        resources:
          requests:
            cpu: "10m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
