// <auto-generated />
using System;
using LoyaltyCustomerService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoyaltyCustomerService.Data.Migrations
{
    [DbContext(typeof(LoyaltyDbContext))]
    [Migration("20260913133428_InitialLoyaltySchema")]
    partial class InitialLoyaltySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LoyaltyCustomerService.Models.ClienteAfiliado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("QrCode")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("qr_code");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("TierId")
                        .HasColumnType("uuid")
                        .HasColumnName("tier_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_clientes_afiliados_tenant");

                    b.HasIndex("TierId");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("idx_clientes_afiliados_tenant_email");

                    b.HasIndex("TenantId", "QrCode")
                        .HasDatabaseName("idx_clientes_afiliados_tenant_qr");

                    b.ToTable("clientes_afiliados");
                });

            modelBuilder.Entity("LoyaltyCustomerService.Models.MovimientoPuntos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<int>("Puntos")
                        .HasColumnType("integer")
                        .HasColumnName("puntos");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("idx_movimientos_puntos_cliente");

                    b.HasIndex("ClienteId", "Timestamp")
                        .HasDatabaseName("idx_movimientos_puntos_cliente_timestamp");

                    b.ToTable("movimientos_puntos");
                });

            modelBuilder.Entity("LoyaltyCustomerService.Models.SaldoPuntos", b =>
                {
                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<int>("PuntosDisponibles")
                        .HasColumnType("integer")
                        .HasColumnName("puntos_disponibles");

                    b.Property<int>("PuntosHistoricos")
                        .HasColumnType("integer")
                        .HasColumnName("puntos_historicos");

                    b.HasKey("ClienteId");

                    b.ToTable("saldos_puntos");
                });

            modelBuilder.Entity("LoyaltyCustomerService.Models.TierMembresia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BeneficiosJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("beneficios_json");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("PuntosMinimos")
                        .HasColumnType("integer")
                        .HasColumnName("puntos_minimos");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_tiers_membresia_tenant");

                    b.ToTable("tiers_membresia");
                });

            modelBuilder.Entity("LoyaltyCustomerService.Models.ClienteAfiliado", b =>
                {
                    b.HasOne("LoyaltyCustomerService.Models.TierMembresia", "Tier")
                        .WithMany("ClientesAfiliados")
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("LoyaltyCustomerService.Models.MovimientoPuntos", b =>
                {
                    b.HasOne("LoyaltyCustomerService.Models.ClienteAfiliado", "Cliente")
                        .WithMany("Movimientos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("LoyaltyCustomerService.Models.SaldoPuntos", b =>
                {
                    b.HasOne("LoyaltyCustomerService.Models.ClienteAfiliado", "Cliente")
                        .WithOne("SaldoPuntos")
                        .HasForeignKey("LoyaltyCustomerService.Models.SaldoPuntos", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("LoyaltyCustomerService.Models.ClienteAfiliado", b =>
                {
                    b.Navigation("Movimientos");

                    b.Navigation("SaldoPuntos");
                });

            modelBuilder.Entity("LoyaltyCustomerService.Models.TierMembresia", b =>
                {
                    b.Navigation("ClientesAfiliados");
                });
#pragma warning restore 612, 618
        }
    }
}
